apiVersion: apps/v1
kind: Deployment
metadata:
  name: jason-app
  labels:
    app: jason-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jason-app
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: jason-app
    spec:
      containers:
      - name: jason-app
        image: gcr.io/lbg-training/jason-node-app:13
        ports:
        - containerPort: 80
